remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Caffeine Chronicles
description: Computer Science Capstone Project by Samael Gamboa, Nehemiah Gordon, Monique Frye, and Graham Christopher Jr.
